name: Continuous Integration
on:
  push:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    name: "Test: Python ${{ matrix.python }} on ${{ matrix.platform }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==2.4.1 poetry-plugin-export==1.10.0
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-venv
        uses: actions/cache@v6
        with:
          path: .venv
          key: venv-${{ matrix.python }}-${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-venv.outputs.cache-hit != 'true'
        run: make install-deps

      - name: Verify generated requirements
        run: make check-generated-requirements

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
